SilverStripe\Control\Director:
  rules:
    'event/$ObfuscatedID': 'PathwayAI\Controllers\EventController'
    'register/$ObfuscatedID': 'PathwayAI\Controllers\RegisterPageController'
    'sign-out': 'PathwayAI\Controllers\SignInPageController'
    'job/$ObfuscatedID': 'PathwayAI\Controllers\JobController'